name: Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: 16
        distribution: 'adopt'
        cache: maven

    - name: Test with Maven
      run: mvn verify
